"""add webhook fields to payments

Revision ID: 2d72c88e24dc
Revises: 0001_create_payments_and_outbox
Create Date: 2026-04-17 18:29:17.442497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2d72c88e24dc'
down_revision: Union[str, None] = '0001_create_payments_and_outbox'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('webhook_attempts', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('webhook_delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('webhook_last_error', sa.Text(), nullable=True))
    op.drop_constraint(op.f('payments_idempotency_key_key'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=False)
    op.create_unique_constraint(op.f('payments_idempotency_key_key'), 'payments', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('payments', 'webhook_last_error')
    op.drop_column('payments', 'webhook_delivered_at')
    op.drop_column('payments', 'webhook_attempts')
    # ### end Alembic commands ###